### ISSUE TITLE
Won't work with Official tabs

### ISSUE THREAD

**Issue by anzenchitai** [noahmaranesi/Ultimate-Guitar-Hack#3]
Your HTML code won't work with official tabs but it works with everything else. Is there a way to download Official tabs?

**Comment by noahmaranesi** [comment]
Hey @anzenchitai thanks for your interest!

I’ve been working with someone for the past few days and we’ve got something coming very shortly. More than likely a tool won’t be released, but it’ll be almost just as helpful.
